#!/bin/sh
case $(arch) in
x86_64)
  readonly ARCH=amd64
  readonly suffix=""
  ;;
aarch64)
  readonly ARCH=arm64
  readonly suffix=-$ARCH
  ;;
*)
  echo "Unsupported $(arch)"
  exit
  ;;
esac
cd "$(dirname "$(readlink -f "$0")")"
set -e
export INSTALL_K3S_BIN_DIR="${INSTALL_K3S_BIN_DIR:-/usr/bin}"    # install.bin
export INSTALL_K3S_DATA_DIR="${INSTALL_K3S_DATA_DIR:-/data/K3S}" # install.data
mkdir -p "$INSTALL_K3S_BIN_DIR" "$INSTALL_K3S_DATA_DIR"
LN_DIR=/etc/rancher && {
  rm -rf "$LN_DIR"
  mkdir -p "$INSTALL_K3S_DATA_DIR" "${LN_DIR%/*}"
  ln -sf "$INSTALL_K3S_DATA_DIR" "$LN_DIR"
}
LN_DIR=/var/lib/rancher/credentialprovider && {
  rm -rf "$LN_DIR"
  mkdir -p "$INSTALL_K3S_DATA_DIR.cred" "${LN_DIR%/*}"
  ln -sf "$INSTALL_K3S_DATA_DIR.cred" "$LN_DIR"
}
LN_DIR=/var/lib/rancher/k3s && {
  rm -rf "$LN_DIR"
  mkdir -p "$INSTALL_K3S_DATA_DIR" "${LN_DIR%/*}"
  ln -sf "$INSTALL_K3S_DATA_DIR" "$LN_DIR"
}
LN_DIR=/var/lib/cni && {
  rm -rf "$LN_DIR"
  mkdir -p "$INSTALL_K3S_DATA_DIR.cni" "${LN_DIR%/*}"
  ln -sf "$INSTALL_K3S_DATA_DIR.cni" "$LN_DIR"
}
LN_DIR=/var/lib/kubelet && {
  rm -rf "$LN_DIR"
  mkdir -p "$INSTALL_K3S_DATA_DIR.kubelet" "${LN_DIR%/*}"
  ln -sf "$INSTALL_K3S_DATA_DIR.kubelet" "$LN_DIR"
}
if [ -s .$ARCH/k3s ]; then
  cp -auv .$ARCH/k3s "$INSTALL_K3S_DATA_DIR/K3S"
else
  wget -qO"$INSTALL_K3S_DATA_DIR/K3S" "https://rancher-mirror.rancher.cn/k3s/${INSTALL_K3S_VERSION:-v1.26.15-k3s1}/k3s$suffix"
fi
echo
env | grep K3S_ | sort
cp -au "$INSTALL_K3S_DATA_DIR/K3S" "$INSTALL_K3S_BIN_DIR/k3s"
chmod a+x "$INSTALL_K3S_BIN_DIR/k3s"
echo
if [ -z "$K3S_CONFIG_FILE" ]; then
  readonly K3S_CONFIG_FILE="/etc/rancher/k3s/config.yaml"
else
  export K3S_CONFIG_FILE
fi
mkdir -p "${K3S_CONFIG_FILE%/*}"
cat <<EOF >"$K3S_CONFIG_FILE"
kubelet-arg:
  - cpu-cfs-quota=false
  - make-iptables-util-chains=true
kube-proxy-arg:
  - proxy-mode=iptables
pause-image: rancher/mirrored-pause:3.6
prefer-bundled-bin: true
token: sensoro
EOF
configagent() {
  cat <<EOF >>"$K3S_CONFIG_FILE"
disable-apiserver-lb: false
EOF
}
configserver() {
  if [ -z "$K3S_URL" ]; then
    cat <<EOF >>"$K3S_CONFIG_FILE"
cluster-init: true
EOF
  fi
  readonly MF=/etc/rancher/server/manifests
  mkdir -p "$MF"
  ls -lth manifests*
  cp -auv manifests/* "$MF"
  if [ -s .$ARCH/k9s ]; then
    cp -au .$ARCH/k9s "$INSTALL_K3S_BIN_DIR"
  fi
  cat <<EOF >>"$K3S_CONFIG_FILE"
embedded-registry: true
cluster-cidr: 172.31.0.0/17
service-cidr: 172.31.128.0/18
cluster-dns: 172.31.128.10
flannel-backend: host-gw
write-kubeconfig: $HOME/.kube/config
write-kubeconfig-mode: 600
helm-job-image: rancher/klipper-helm:v0.9.2-build20240828
disable:
 - servicelb
 - traefik
disable-cloud-controller: true
disable-network-policy: true
disable-helm-controller: false
node-label:
 - operator
EOF
}
registries() {
  cat <<EOF >"${K3S_CONFIG_FILE%/*}/registries.yaml"
mirrors:
  "*":
    endpoint:
      - https://harbor.sensoro.com
configs:
  harbor.sensoro.com:
    auth:
      username: user
      password: pass
EOF
}
if ! [ -s k3s-install.sh ]; then
  wget -qO- https://rancher-mirror.rancher.cn/k3s/k3s-install.sh |
    sed "s~create_env_file$~create_env_file;echo CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS=$((365 * 5)) >>\$FILE_K3S_ENV~" >k3s-install.sh
fi
if ! k3s check-config; then
  k3s-killall.sh >/dev/null 2>&1 || true
  exit
fi
registries
if echo "$*" | grep -q agent; then
  configagent
else
  configserver
fi
export INSTALL_K3S_FORCE_RESTART=true
export INSTALL_K3S_SKIP_DOWNLOAD=true
export INSTALL_K3S_SYMLINK=force
exec sh k3s-install.sh "$@"
