#!/bin/bash
set -e

SCRIPT_DIR=$(dirname $0)
pushd $SCRIPT_DIR
export ARCH=$(go env GOHOSTARCH)
go mod tidy
go mod vendor
git diff | grep "^[+-]" || true
./download
./validate
./build
./package

popd

$SCRIPT_DIR/binary_size_check.sh
